services:
  - type: web
    name: salomao
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://seu-app.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: supabase
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_FRONTEND_API_URL
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: INERTIA_SSR_ENABLED
        value: false
      - key: INERTIA_USE_SCRIPT_ELEMENT_FOR_INITIAL_PAGE
        value: true
